version: '3'

services:
  postgres:
    container_name: elefante
    image: postgres:latest
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=osworks
    volumes:
      - /mnt/DEV/docker-dados/postgresqldados:/var/opt/postgresql/data
