version: '3'

services:
  postgres:
    container_name: elefante
    image: postgres:latest
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456

    volumes:
      - F:\mnt\DEV\docker-dados\postgresqldados:/var/opt/postgresql/data  
      #F:\DEV\docker-dados\postgresqldados